---
- name: Perform apt update 
  apt:
     upgrade: yes
     upgade_cache: yes

- name: Install needed packages
  apt:
    pkg:
       - bridge-utils
       - cpu-checker
       - libvirt-clients
       - libvirt-daemon
       - libvirt-daemon-system
       - qemu
       - qemu-kvm
       - libguestfs-tools
       - virtinst
       - python3-lxml
       - python3-libvirt
    state: latest
    update_cache: true

- name: Add users to group for furure authorization
  user:
     name: ymchornyi
     groups:
      - kvm
      - libvirt
- name: Ensure libvirt service is running
  service:
     name: libvirtd
     state: started

   
